In [2]:
#pip install numpy

In [3]:
import numpy as np

In [5]:
a=np.array(70)
print(a)
print(type(a))
print(a.ndim)

70
<class 'numpy.ndarray'>
0


In [6]:
b=np.array([1,2,3,4])
print(b)
print(type(b))
print(b.ndim)

[1 2 3 4]
<class 'numpy.ndarray'>
1


In [9]:
c=np.array([[1,2,3],[4,5,6]])
print(c)
print(type(c))
print(c.ndim)

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2


In [11]:
c=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(c)
print(type(c))
print(c.ndim)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
<class 'numpy.ndarray'>
3


In [20]:
d=np.array([3,5.6,"python",7+9j,'True','False'])
print(d)
print(type(d))
print(d.ndim)

['3' '5.6' 'python' '(7+9j)' 'True' 'False']
<class 'numpy.ndarray'>
1


In [13]:
a=[1,2,3,4,5]
b=[5,6,7,8,9]
print(a+b)

[1, 2, 3, 4, 5, 5, 6, 7, 8, 9]


In [15]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])
print(a+b)

[ 6  8 10 12 14]


In [16]:
print(sum(a))

15


In [17]:
print(sum(b))

35


In [18]:
d=np.mean(a)
print(d)

3.0


In [19]:
e=np.mean(b)
print(e)

7.0
